OPSEXP-590  Addition of cleanup and uninstallation playbook.
Alfresco/alfresco-ansible-deployment pull request #388
Opened 2022-07-21 10:07 UTC by slohe1

Cleanup and Uninstallation playbook added along with updated documentation.

2022-07-21 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-ansible-deployment?pullRequest=388) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-ansible-deployment?pullRequest=388) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-ansible-deployment?pullRequest=388) it.</sub>

2022-07-21 12:15 UTC, alxgomz commented on docs/deployment-guide.md
> +This playbook will remove the temporary artifacts which are stored on the hosts.In order to cleanup the system post deployment run the following command:
Can you add a reminder about the fact running that playbook breaks playbook idempotency?

2022-07-21 12:16 UTC, alxgomz commented on docs/deployment-guide.md
> +This playbook will uninstall the sevices belongs to the specific hosts. Below are the services, packages & folders we are removing as the uninstalltions
```suggestion
This playbook will uninstall the sevices which belong to the specific hosts. Below are the services, packages & folders we are removing when uninstalling 
```

2022-07-21 12:19 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +
Please avoid white space at the beginning of the file

2022-07-21 12:20 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +         enabled: no
unnecessary as we remove the package later on and the service is deployed with the package

2022-07-21 12:23 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +         state: absent
Please use  `autoremove: yes` (`ansible.builtin.package` is just a wrapper for apt, dnf & yum  modules, so every option that's valid for all package managers is valid.

2022-07-21 12:25 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +         enabled: no
Do not forget to remove the systemd unit file as well. This one is not installed by a package so needs to be removed  by the playbook (and systemd reloaded using an handler)

2022-07-21 12:26 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +     - name: Removing activemq folders
```suggestion
     - name: Removing Java folders
```

2022-07-21 12:29 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +
Also. do not forget to cleanup the systemd unit files and reload daemon

2022-07-21 12:29 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +     - name: Removing activemq folders
same as above. this is Java not activemq

2022-07-21 12:29 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +         enabled: no
same as above

2022-07-21 12:29 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +         enabled: no
same as above.

2022-07-21 12:30 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +     - name: Removing activemq folders
java not activemq

2022-07-21 12:30 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +         enabled: no
we don't need that as we remove the pkg

2022-07-21 12:37 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +        - "{{ download_location | default('/tmp/ansible_artefacts') }}"
these one are not repository specific. Also transformers, search, syncservice have these folders

2022-07-21 12:38 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +        - "{{ download_location | default('/tmp/ansible_artefacts') }}"
actually `{{ config_folder }}` might even be required elsewhere

2022-07-22 17:07 UTC, alxgomz requested changes
please address remaining comment.
In particular take a look at the doc for ansible handlers and use it to reload systemd after a unit file is removed

2022-07-22 17:07 UTC, alxgomz commented on playbooks/platform-uninstall.yml
> +        - "{{ tomcat_home_prefix | default('/opt/apache-tomcat') }}"
missing the unit file

2022-07-25 08:11 UTC, alxgomz requested changes
Please DRY. Use include statements in each play and have the handler defined only once in a separate file (e.g. `uninstall-handlers.yml`).
Also the pre-commi stage is still failing, please make sure to run pre-commit before pushing

2022-07-25 15:11 UTC, gionn requested changes
we should run this playbook as part of a molecule run, maybe we can hook it in the [cleanup](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/molecule/default/cleanup.yml) phase?

2022-07-29 07:36 UTC, gionn requested changes
see https://github.com/Alfresco/alfresco-ansible-deployment/runs/7561678936?check_suite_focus=true#step:11:127

2022-07-29 08:51 UTC, slohe1 commented
> see https://github.com/Alfresco/alfresco-ansible-deployment/runs/7561678936?check_suite_focus=true#step:11:127

2022-07-29 08:56 UTC, slohe1 commented
https://github.com/Alfresco/alfresco-ansible-deployment/pull/388#pullrequestreview-1055130 
Here looks like TASK [Removing the Packages]  passed. Stopping the playbook at next play. Just trying to get why it is different for this instance.

2022-08-02 13:17 UTC, gionn approved these changes

2022-08-02 13:19 UTC, merged