OPSEXP-1649 Uninstall Playbook Fails At Clustered EC2 Tests
Alfresco/alfresco-ansible-deployment pull request #469
Opened 2022-10-06 07:51 UTC by upandey123

Fixed cleanup.yml and platform-uninstall.yml files

2022-10-06 07:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-ansible-deployment?pullRequest=469) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-ansible-deployment?pullRequest=469) before we can accept your contribution.<br/><hr/>**Utkarsh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-ansible-deployment?pullRequest=469) it.</sub>

2022-10-06 11:59 UTC, alxgomz requested changes

2022-10-06 11:59 UTC, alxgomz commented on molecule/multimachine/cleanup.yml
> +  import_playbook: ../default/cleanup-uninstall.yml
This must be wrong given the results of the `multimachine` build stage

2022-10-11 06:59 UTC, alxgomz requested changes
Your branch as some conflict with the merge target now. Please rebase from master.

2022-10-11 06:59 UTC, alxgomz commented on molecule/multimachine/cleanup.yml
> +
remove double blank lines pls

2022-10-11 06:59 UTC, alxgomz commented on molecule/multimachine/prepare.yml
> +    #broker_name: molecule-{{ lookup('env', 'BUILD_NUMBER') }}
Remove this comment pls

2022-10-11 15:21 UTC, alxgomz approved these changes

2022-10-11 15:23 UTC, alxgomz requested changes

2022-10-11 15:23 UTC, alxgomz commented on molecule/multimachine/cleanup.yml
> +
this one remains

2022-10-11 15:23 UTC, alxgomz commented on molecule/multimachine/cleanup.yml
> +    broker_name: molecule-{{ lookup('ansible.builtin.env', 'BRANCH_NAME')[:42] }}-{{ lookup('ansible.builtin.env', 'BUILD_NUMBER') }}
This breaks the pre-commit checks

2022-10-12 08:04 UTC, upandey123 commented on molecule/multimachine/cleanup.yml
> +    broker_name: molecule-{{ lookup('ansible.builtin.env', 'BRANCH_NAME')[:42] }}-{{ lookup('ansible.builtin.env', 'BUILD_NUMBER') }}
fixed the pre commit checks.

2022-10-12 08:04 UTC, upandey123 commented on molecule/multimachine/cleanup.yml
> +
fixed that one too.

2022-10-12 10:52 UTC, gionn approved these changes

2022-10-12 12:22 UTC, merged