OPSEXP-1770 Support for Ubuntu-22.04
Alfresco/alfresco-ansible-deployment pull request #477
Opened 2022-10-14 08:56 UTC by slohe1

2022-10-14 12:12 UTC, alxgomz requested changes
First of all this one cannot yet be merged to master. but should instead go to `next/acs-7.3` Also make sure to update the documentation as per [https://github.com/Alfresco/alfresco-ansible-deployment/blob/OPSEXP-1769/docs/developer-guide.md#adding-support-for-a-new-distribution (this doc is still to be merged but relevant)](https://github.com/Alfresco/alfresco-ansible-deployment/blob/next/acs-7.3/docs/developer-guide.md#adding-support-for-a-new-distribution)

2022-10-17 07:43 UTC, gionn requested changes

2022-10-17 07:43 UTC, gionn commented on .github/workflows/enteprise.yml
> +            desc: EC2 ACS 7.2 Community (Ubuntu 22.04)
you should probably delete the vars-ubuntu20-community.yml file

2022-10-17 09:41 UTC, gionn approved these changes

2022-10-17 10:13 UTC, alxgomz approved these changes

2022-10-17 17:26 UTC, merged