OPSEXP-1833 Bump imagemagick package version
Alfresco/alfresco-ansible-deployment pull request #506
Opened 2022-11-16 14:25 UTC by slohe1

OPSEXP-1833

2022-11-16 14:33 UTC, alxgomz submitted a review, later dismissed
That's not very sustainable.
make the suffix part of the version variable, or - if not possible - create a new suffix variable to append in var files.
That way we only have one place where we need to fix things in case we update that release build number

2022-11-16 14:59 UTC, slohe1 commented
> That's not very sustainable. make the suffix part of the version variable, or - if not possible - create a new suffix variable to append in var files. That way we only have one place where we need to fix things in case we update that release build number

Bumped a new variable "imagemagick_release" under dependencies_version so that its one place for both imagemagick version & release number

2022-11-17 09:05 UTC, gionn commented on roles/transformers/vars/CentOS7.yml
> +imagemagick_version: "{{ dependencies_version.imagemagick }}-ci-{{ dependencies_version.imagemagick_release }}"
I still think that just using`dependencies_version.imagemagick` would be simpler and gives more flexibility on the package version

2022-11-17 13:35 UTC, gionn requested changes
looking at the test failures it seems we have a problem with RHEL 8, `test_get_rendition` is always failing on integration tests

then it seems there is a problem running `libreoffice` in the transformers role tests [link](https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/3487299672/jobs/5834772497#step:7:1667)

2022-11-18 11:52 UTC, gionn approved these changes

2022-11-18 12:13 UTC, merged