Fix OS test condition and RedHat ansible distribution name
Alfresco/alfresco-ansible-deployment pull request #559
Opened 2023-03-17 11:41 UTC by morgan-patou

Description:
Task with name "- name: Compare host OS with supported matrix" is currently being skipped most of the time. This is because "skip_os_test" is undefined and because "ansible_distribution_version | int not in os_versions" is failing as well. The transformation to "INT" means that only the major version is kept (E.g.: RedHat 8.6 >> 8). Since "8" is never present in "os_versions" (which contains 8.2, 8.5, 8.6, etc.), then this check is always skipped. According to the documentation, it is supposed to be the opposite, meaning that it's always executed, except if "-i skip_os_test=true" is added as extra var.

Also, the correct ansible distribution for RedHat is "RedHat" and not "RHEL". This causes the "supported_os" to not find anything in case the target OS is RedHat, c.f. https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html#ansible-facts-distribution.

Solution:
This PR includes the switch from "RHEL" to "RedHat" in the group_vars/all.yml file as well as the fix of the conditions so that the check is always executed and gives the expected result, meaning:
1. failure if distribution/version doesn't match what is defined in the group_vars/all.yml file
2. skipping if distribution/version matches OR if skip_os_test=true

Please review

2023-03-17 11:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-ansible-deployment?pullRequest=559) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-ansible-deployment?pullRequest=559) before we can accept your contribution.<br/><hr/>**Morgan Patou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-ansible-deployment?pullRequest=559) it.</sub>

2023-03-18 12:03 UTC, alxgomz requested changes
Well spotted! Thanks for the contribution. Just one small suggestion, but that's all OK to move it forward.

2023-03-20 07:41 UTC, morgan-patou commented
Works for me with this alternative definition. I quickly tested the different possibilities (supported, unsupported, without and with false/true for the skip_os_test), no problems spotted.

2023-03-20 08:13 UTC, gionn reviewed
There are a few test failures that expose that we missed updating the supported os matrix due to the bug you just fixed.

Rocky 8.6 and 8.7 should be added for sure, not sure about CentOS 7.7 that is an old version and I suppose we need to bump the AMI we are testing against.

up to you if you want to try to tackle also this last issues in order to obtain a green build, or just put this PR on hold and I can try to take a look soon and raise another PR to fix those tests.

2023-03-22 14:40 UTC, morgan-patou commented
> There are a few test failures that expose that we missed updating the supported os matrix due to the bug you just fixed.
> 
> Rocky 8.6 and 8.7 should be added for sure, not sure about CentOS 7.7 that is an old version and I suppose we need to bump the AMI we are testing against.
> 
> up to you if you want to try to tackle also this last issues in order to obtain a green build, or just put this PR on hold and I can try to take a look soon and raise another PR to fix those tests (internally tracked as [OPSEXP-2047](https://alfresco.atlassian.net/browse/OPSEXP-2047)).

If needed I can modify the group_vars/all.yml to include Rocky and CentOS versions mentioned but I do not know if you have any other steps to perform to include a new OS? Do you have some guidelines with the list of all steps? I would also need some details on which ACS versions are supported on these 2 OS, so I can update the doc as well. Currently CentOS 7.7 is marked as supported for all ACS versions from 6.2 to 7.3, including Community as well.

2023-03-22 15:31 UTC, gionn commented
> If needed I can modify the group_vars/all.yml to include Rocky and CentOS versions mentioned but I do not know if you have any other steps to perform to include a new OS?

You should just really need to add Rocky 8.6, Rocky 8.7, CentOS 7.7

docs should be fine https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/README.md#versioning

thanks again!

2023-03-23 07:51 UTC, gionn approved these changes

2023-03-23 09:23 UTC, alxgomz approved these changes
OK to merge as-is for now but we'll need another task to update our centos AMI and drop the support for centos 7.7 as most ACS version actually specify 7.9

2023-03-23 09:48 UTC, merged