OPSEXP-2290: fix sync service and transformation configs
Alfresco/alfresco-ansible-deployment pull request #681
Opened 2023-10-03 14:48 UTC by alxgomz

Ref: OPSEXP-2290
transformation config changed in  https://github.com/Alfresco/alfresco-enterprise-repo/pull/1359
Sync service role just needed to work from the distributed file rather than local templates

2023-10-04 07:18 UTC, gionn requested changes
I would prefer having those changes on master since there is no reason to gate them until next release (except for the version bumps of course)

2023-10-04 07:18 UTC, gionn commented on molecule/multimachine/host_vars/repository_neutron.yml
> +cluster_keepoff: false  # workaround while investigatinfclusering issues
raise a new issue and reference it there? or at least fix the typos 😀

2023-10-04 10:37 UTC, alxgomz commented
> I would prefer having those changes on master since there is no reason to gate them until next release (except for the version bumps of course)

This taskl being part of the 23.1 readiness epic the target branch is for now next/acs-23.1

2023-10-05 08:50 UTC, gionn approved these changes

2023-10-05 10:11 UTC, merged