OPSEXP-2551 Fixup redirect url configuration for adw/acc
Alfresco/alfresco-ansible-deployment pull request #807
Opened 2024-03-05 14:30 UTC by gionn

Ref: OPSEXP-2551

2024-03-05 15:55 UTC, alxgomz reviewed
I think we should instead have a generic role param that states the context of the app, and build URLs from the role itself using this param.
What do you think?

2024-03-06 09:40 UTC, alxgomz requested changes
Implementation works for me but if I read it correctly, you're not passing the `adf_app_context` so it'll default to `adf_app_name`  which are actually different from the current contexts we have:
alfresco-digital-workspace = > /workspace/
alfresco-control-center => /control-center/

2024-03-06 13:17 UTC, gionn commented
> you're not passing the `adf_app_context`

just a bug, now there are tests to properly validate it

2024-03-07 09:06 UTC, alxgomz approved these changes

2024-03-07 09:34 UTC, merged