OPSEXP-2466 Remove CI for 7.1 and 7.2
Alfresco/alfresco-ansible-deployment pull request #824
Opened 2024-04-04 09:18 UTC by pmacius

Ref: OPSEXP-2466

2024-04-04 11:16 UTC, pmacius commented
I created a task for enabling manual trigger for older versions: https://hyland.atlassian.net/browse/OPSEXP-2610

2024-04-04 13:37 UTC, gionn requested changes

2024-04-04 13:37 UTC, gionn commented on molecule/default/vars-rhel8.yml
> +MOLECULE_IT_IMAGE_ID: ami-0f0f1c02e5e4d9d9f # RHEL-8.6.0_HVM-20220503-x86_64-2-Hourly2-GP
```suggestion
MOLECULE_IT_IMAGE_ID: ami-0053c27847a0ea3cd # RHEL-8.6.0_HVM-20240229-x86_64-19-Hourly2-GP3
```

2024-04-04 13:37 UTC, gionn commented on molecule/default/vars-rhel8.yml
> +MOLECULE_IT_IMAGE_ID: ami-0f0f1c02e5e4d9d9f # RHEL-8.6.0_HVM-20220503-x86_64-2-Hourly2-GP
<img width="1798" alt="Screenshot 2024-04-04 at 15 37 11" src="https://github.com/Alfresco/alfresco-ansible-deployment/assets/71768/934c342b-ca14-4cda-b782-49cbc082b7b1">

2024-04-04 15:52 UTC, alxgomz approved these changes

2024-04-05 07:53 UTC, gionn approved these changes

2024-04-05 07:54 UTC, merged