OPSEXP-2554 Using a password with $ for activemq break everything in ansible deployment
Alfresco/alfresco-ansible-deployment pull request #862
Opened 2024-05-15 07:59 UTC by pmacius

Ref: OPSEXP-2554

2024-05-20 09:14 UTC, pmacius commented on roles/transformers/templates/alfresco-tengine-aio.service.j2
> +{% set java_opts = java_opts + " " + tengine_environment_temp|join(' ') %}
Im not sue if this is the best way to do it.

2024-05-21 10:06 UTC, gionn commented on roles/transformers/templates/alfresco-tengine-aio.service.j2
> +{%- if pkg_format == 'deb' -%}
probably better to use `ansible_os_family` or `ansible_distribution` if needs to be more specific

2024-05-21 10:06 UTC, gionn commented on roles/transformers/templates/alfresco-tengine-aio.service.j2
> +{%- macro standrad_output_macro() -%}
also check typo

2024-05-21 11:59 UTC, pmacius commented on molecule/pki/verify.yml
> +          edition: Enterprise
Decided to add this additional task due:
https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/9172660358/job/25219680867

2024-05-22 07:14 UTC, gionn commented on molecule/pki/verify.yml
> +    - name: Check in logs a client did connect
use set_facts to populate a var depending on the os family to be feed to the `loop` structure so you don't duplicate the entire slurp task

2024-05-22 07:14 UTC, gionn commented on roles/transformers/tasks/main.yml
> +    - name: Delete startup script
```suggestion
    - name: Delete deprecated startup script
```

minor: move this task where the `Add AIO startup script` was

2024-05-22 09:49 UTC, gionn requested changes

2024-05-22 09:49 UTC, gionn commented on molecule/pki/verify.yml
> +            edition: Enterprise
oh wait, but you can just make sure that both platforms produced the same logs file by using a more complex loop structure like:

```
- service_name: alfresco-tengine-aio
  file_name: ats-ate-aio
```

2024-05-27 14:05 UTC, gionn approved these changes

2024-05-27 14:17 UTC, merged