OPSEXP-2747 Avoid configuring repository with search enterprise for community
Alfresco/alfresco-ansible-deployment pull request #908
Opened 2024-07-22 15:23 UTC by gionn

ref: OPSEXP-2747

2024-07-22 16:03 UTC, alxgomz requested changes
Please add a pre-check which fails the play in case inventory is configured with community edition awith search enterprise hosts and no search hosts and always skip searc enterprise play when community is set

2024-07-23 08:36 UTC, pmacius approved these changes

2024-07-23 08:38 UTC, gionn commented on inventory_local.yml
> +    # Solr search engine (alternative to Enterprise Search - only option for Community)
```suggestion
    # Solr search engine (an alternative to Enterprise Search, and the only available option for the Community edition)
```

2024-07-23 08:39 UTC, gionn commented on inventory_local.yml
> +    # Enterprise Search (default search engine - not available for Community)
```suggestion
    # Enterprise Search (default search engine - not available in Community edition)
```

2024-07-23 08:39 UTC, gionn commented on inventory_ssh.yml
> +    # Solr search engine (alternative to Enterprise Search - only option for Community)
```suggestion
    # Solr search engine (an alternative to Enterprise Search, and the only available option for the Community edition)
```

2024-07-23 08:39 UTC, gionn commented on inventory_ssh.yml
> +    # Enterprise Search (default search engine - not available for Community)
```suggestion
    # Enterprise Search (default search engine - not available in Community edition)
```

2024-07-23 13:14 UTC, alxgomz approved these changes

2024-07-23 13:27 UTC, merged