OPSEXP-2147 Drop helper_modules role
Alfresco/alfresco-ansible-deployment pull request #956
Opened 2024-09-30 12:35 UTC by gionn

OPSEXP-2147

2024-10-01 08:31 UTC, alxgomz requested changes

2024-10-01 08:31 UTC, alxgomz commented on playbooks/prerun-network-checks.yml
> +        checked_host: "{{ hostvars[groups.database[0]].ansible_host | default('localhost') }}"
actually we should probablyuse `{{ db_host }}` as that's what's used in the repo role to connect to the db
https://github.com/Alfresco/alfresco-ansible-deployment/blob/fe23ffa25bea1ee545a69f57b8f555e88d2e03c4/roles/common/defaults/main.yml#L43

2024-10-01 08:31 UTC, alxgomz commented on playbooks/prerun-network-checks.yml
> +        checked_host: "{{ hostvars[groups.activemq[0]].ansible_host | default('localhost') }}"
Same as above: `activemq_host`
https://github.com/Alfresco/alfresco-ansible-deployment/blob/fe23ffa25bea1ee545a69f57b8f555e88d2e03c4/roles/common/defaults/main.yml#L31

2024-10-01 08:31 UTC, alxgomz commented on playbooks/prerun-network-checks.yml
> -        checked_host: "{% if groups.syncservice | length == 0 %}127.0.0.1{% else %}{{ hostvars[groups.syncservice[0]].ansible_host | default('127.0.0.1') }}{% endif %}"
`sync_host`
https://github.com/Alfresco/alfresco-ansible-deployment/blob/fe23ffa25bea1ee545a69f57b8f555e88d2e03c4/roles/common/defaults/main.yml#L85

2024-10-01 08:31 UTC, alxgomz commented on playbooks/prerun-network-checks.yml
> +        checked_host: "{{ hostvars[groups.search[0]].ansible_host | default('localhost') }}"
`solr_host`
https://github.com/Alfresco/alfresco-ansible-deployment/blob/fe23ffa25bea1ee545a69f57b8f555e88d2e03c4/roles/common/defaults/main.yml#L49C1-L49C10

2024-10-01 08:31 UTC, alxgomz commented on playbooks/prerun-network-checks.yml
> +        checked_host: "{{ hostvars[groups.transformers[0]].ansible_host | default('localhost') }}"
`sfs_host`
https://github.com/Alfresco/alfresco-ansible-deployment/blob/fe23ffa25bea1ee545a69f57b8f555e88d2e03c4/roles/common/defaults/main.yml#L61

2024-10-01 08:31 UTC, alxgomz commented on playbooks/prerun-network-checks.yml
> -        - acs.edition == "Enterprise"
Why are you excluding the enterprise ersion condition for sync and adding it for ats?

2024-10-01 08:31 UTC, alxgomz commented on playbooks/prerun-network-checks.yml
> +        checked_host: "{{ hostvars[groups.transformers[0]].ansible_host | default('localhost') }}"
`trouter_host`
https://github.com/Alfresco/alfresco-ansible-deployment/blob/fe23ffa25bea1ee545a69f57b8f555e88d2e03c4/roles/common/defaults/main.yml#L67

2024-10-01 08:31 UTC, alxgomz commented on playbooks/prerun-network-checks.yml
> +        checked_host: "{{ hostvars[groups.transformers[0]].ansible_host | default('localhost') }}"
`ats_tengine_aio_host`
https://github.com/Alfresco/alfresco-ansible-deployment/blob/fe23ffa25bea1ee545a69f57b8f555e88d2e03c4/roles/common/defaults/main.yml#L55C1-L55C21

2024-10-02 07:58 UTC, gionn commented on molecule/prerun_network_checks/host_vars/instance.yml
> +# END KNOWN_URLS VAR
```suggestion
```

2024-10-02 07:58 UTC, gionn commented on playbooks/tasks/check_port.yml
> +    - molecule-idempotence-notest
listen is not idempotent so skipping everything

2024-10-02 08:17 UTC, pmacius approved these changes
Did't catch anything - looks good

2024-10-02 20:06 UTC, alxgomz approved these changes

2024-10-03 15:17 UTC, merged